services:
  honeypot:
    image: ghcr.io/l3montree-dev/oh-my-honeypot:v1.0.1
    volumes:
    - "./events.log:/go/src/app/events.log"
    - "./payloads:/go/src/app/payloads"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: honeypot
    ports:
    - 80:80
    - 22:22
    - 23:23
    - 547:547
    - 21:21
    - 25:25
    - 143:143
    - 993:993
    - 2379:2379
    - 88:88
    - 636:636
    - 110:110
    - 8001:8001
    - 990:990
    - 389:389
    - 6443:6443
    - 3306:3306
    - 10255:10255
    - 2380:2380
    - 10252:10252
    - 995:995
    - 10251:10251
    - 989:989
    - 546:546
    - 465:465
    - 10250:10250
    - 67:67
    - 68:68
    - 514:514
    - 123:123
    - 1112:1112
  db:
    image: postgres:16.2
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: honeypot
    volumes:
    - db:/var/lib/postgresql/data
volumes:
  db: {}



