http:
  headers:
    Content-Type: application/json
    X-Custom-Header: CustomValue
  env:
    SSH_USER: rinsalussh
    SSH_PASSWORD: 7ebo0ERCCwnISSH
    DB_HOST: localhost
    DB_USER: ensayouria
    DB_NAME: bankamemdb
    DB_PASSWORD: aYCV6umBuDNHUDB
ssh:
  ServerVersion: SSH-2.0-OpenSSH_5.8p2